version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: static/css
- url: /fonts
  static_dir: static/fonts
- url: /js
  static_dir: static/js
- url: /.*
  script: code.app
